name: CI/CD Pipeline 
 
on: 
  push: 
    branches: 
      - main   # runs when code is pushed 
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
 
    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v3 
 
      - name: Install Dependencies 
        run: npm install 
 
     - name: Build Check 
       run: echo "Build successful"